defaults: &defaults
  working_directory: ~/gutargu
  docker:
    - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
          - api-default
      - run: cd ~/gutargu/api && gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: api-{{ checksum "api/build.gradle" }}
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
      - run: cd ~/gutargu/api && gradle test
  package:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
      - run: cd ~/gutargu/api && gradle bootJar
      - persist_to_workspace:
          root: api/build
          paths:
            - libs/
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: api/build
      - setup_remote_docker
      - run: |
          cd ~/gutargu/api && docker build -t $DOCKER_USER/gutargu-api:$CIRCLE_SHA1 .
          cd ~/gutargu/api && docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd ~/gutargu/api && docker push $DOCKER_USER/gutargu-api:$CIRCLE_SHA1
  deploy:
    working_directory: ~/gutargu
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCLOUD_KEY | base64 --decode > gcloud.p12
          gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
          gcloud --quiet config set project $GCLOUD_PROJECT_NAME
          gcloud --quiet config set container/cluster $GCLOUD_CLUSTER_NAME
          gcloud --quiet config set compute/zone ${GCLOUD_COMPUTE_ZONE}
          gcloud --quiet config set container/use_application_default_credentials true
          gcloud --quiet config set container/use_client_certificate true
          gcloud --quiet container clusters get-credentials $GCLOUD_CLUSTER_NAME
          kubectl patch deployment gutargu-api -p '{"spec":{"template":{"spec":{"containers":[{"name":"gutargu-api","image":"$DOCKER_USER/gutargu-api:'"$CIRCLE_SHA1"'"}]}}}}'
workflows:
  version: 2
  build-test-package-and-publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      - publish:
          requires:
            - package
      - deploy:
          requires:
            - publish
