version: 1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/gutargu
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
          - api-default
      - run: cd ~/gutargu/api && gradle dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: api-{{ checksum "api/build.gradle" }}
      - run: cd ~/gutargu/api && gradle test
      - run: cd ~/gutargu/api && gradle bootJar
      - setup_remote_docker
      - run: |
          cd ~/gutargu/api && docker build -t vivekjain10/gutargu-api .
          cd ~/gutargu/api && docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push vivekjain10/gutargu-api
