defaults: &defaults
  working_directory: ~/gutargu
  docker:
    - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
          - api-default
      - run: cd ~/gutargu/api && gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: api-{{ checksum "api/build.gradle" }}
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
      - run: cd ~/gutargu/api && gradle test
  package:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - api-{{ checksum "api/build.gradle" }}
      - run: cd ~/gutargu/api && gradle bootJar
      - persist_to_workspace:
          root: api/build
          paths:
            - libs/
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: api/build
      - setup_remote_docker
      - run: |
          cd ~/gutargu/api && docker build -t vivekjain10/gutargu-api .
          cd ~/gutargu/api && docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd ~/gutargu/api && docker push vivekjain10/gutargu-api
workflows:
  version: 2
  build-test-package-and-publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      - publish:
          requires:
            - package
